name: MAIN

on:
  push:
    branches: [ main ]  # or your deployment branch
  workflow_dispatch:    # allows manual triggering from the GitHub UI

permissions:
  contents: read
  packages: write  # required to push to GHCR
  id-token: write

jobs:
  build-producer:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: producer

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker image tag
        id: vars
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/producer
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:latest .

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:latest

  build-consumer:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: consumer

    needs: 
    - build-producer

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker image tag
        id: vars
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/consumer
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:latest .

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:latest
